#include "engineDataDefs.h"
using namespace std;

const vector<dataDef> AircraftCommonDefs = {
    { "FUEL LEFT QUANTITY", "liter", SIMCONNECT_DATATYPE_FLOAT64, 0.02 },
    { "FUEL RIGHT QUANTITY", "liter", SIMCONNECT_DATATYPE_FLOAT64, 0.02 },
    { "FUEL TOTAL QUANTITY", "liter", SIMCONNECT_DATATYPE_FLOAT64, 0.02 },
    { "ENG FUEL FLOW GPH:1", "liter per hour", SIMCONNECT_DATATYPE_FLOAT64, 0.005 },
    { "ENG FUEL FLOW GPH:2", "liter per hour", SIMCONNECT_DATATYPE_FLOAT64, 0.005 },
    { "ENG FUEL FLOW GPH:3", "liter per hour", SIMCONNECT_DATATYPE_FLOAT64, 0.005 },
    { "ENG FUEL FLOW GPH:4", "liter per hour", SIMCONNECT_DATATYPE_FLOAT64, 0.005 },
    { "ENG FUEL FLOW PPH:1", "kilograms per second", SIMCONNECT_DATATYPE_FLOAT64, 0.00003 },
    { "ENG FUEL FLOW PPH:2", "kilograms per second", SIMCONNECT_DATATYPE_FLOAT64, 0.00003 },
    { "ENG FUEL FLOW PPH:3", "kilograms per second", SIMCONNECT_DATATYPE_FLOAT64, 0.00003 },
    { "ENG FUEL FLOW PPH:4", "kilograms per second", SIMCONNECT_DATATYPE_FLOAT64, 0.00003 },
    { "GENERAL ENG OIL TEMPERATURE:1", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.1 },
    { "GENERAL ENG OIL TEMPERATURE:2", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.1 },
    { "GENERAL ENG OIL TEMPERATURE:3", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.1 },
    { "GENERAL ENG OIL TEMPERATURE:4", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.1 },
    { "GENERAL ENG OIL PRESSURE:1", "kpa", SIMCONNECT_DATATYPE_FLOAT64, 0.8 },
    { "GENERAL ENG OIL PRESSURE:2", "kpa", SIMCONNECT_DATATYPE_FLOAT64, 0.8 },
    { "GENERAL ENG OIL PRESSURE:3", "kpa", SIMCONNECT_DATATYPE_FLOAT64, 0.8 },
    { "GENERAL ENG OIL PRESSURE:4", "kpa", SIMCONNECT_DATATYPE_FLOAT64, 0.8 },
    { "APU PCT RPM", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.5 },
    { "TRAILING EDGE FLAPS LEFT ANGLE", "degrees", SIMCONNECT_DATATYPE_FLOAT64, 0.5 },
    { "TRAILING EDGE FLAPS RIGHT ANGLE", "degrees", SIMCONNECT_DATATYPE_FLOAT64, 0.5},
    { "SPOILERS LEFT POSITION", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.5 },
    { "SPOILERS RIGHT POSITION", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.5 },
    { "ELEVATOR TRIM PCT", "percent Over 100", SIMCONNECT_DATATYPE_FLOAT64, 0.002 },
    { "RUDDER TRIM PCT", "percent Over 100", SIMCONNECT_DATATYPE_FLOAT64, 0.002 },
    { "AILERON TRIM PCT", "percent Over 100", SIMCONNECT_DATATYPE_FLOAT64, 0.002 }
};

const vector<dataDef> JetDefs = {
    { "TURB ENG N1:1", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG N1:2", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG N1:3", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG N1:4", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG N2:1", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG N2:2", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG N2:3", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG N2:4", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG ITT:1", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.5 },
    { "TURB ENG ITT:2", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.5 },
    { "TURB ENG ITT:3", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.5 },
    { "TURB ENG ITT:4", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.5 },
};

const vector<dataDef> PropDefs = {
    { "GENERAL ENG RPM:1", "rpm", SIMCONNECT_DATATYPE_FLOAT64, 1.0 },
    { "GENERAL ENG RPM:2", "rpm", SIMCONNECT_DATATYPE_FLOAT64, 1.0 },
    { "PROP RPM:1", "rpm", SIMCONNECT_DATATYPE_FLOAT64, 1 },
    { "PROP RPM:2", "rpm", SIMCONNECT_DATATYPE_FLOAT64, 1 },
    { "RECIP ENG MANIFOLD PRESSURE:1", "kpa", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "RECIP ENG MANIFOLD PRESSURE:2", "kpa", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "RECIP ENG BRAKE POWER:1", "ft lb per second", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "RECIP ENG BRAKE POWER:2", "ft lb per second", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "GENERAL ENG EXHAUST GAS TEMPERATURE:1", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.1 },
    { "GENERAL ENG EXHAUST GAS TEMPERATURE:2", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.1 }
};

const vector<dataDef> TurbopropDefs = {
    { "TURB ENG N1:1", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG N1:2", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG FREE TURBINE TORQUE:1", "Newton meter", SIMCONNECT_DATATYPE_FLOAT64, 1.0 },
    { "TURB ENG FREE TURBINE TORQUE:1", "Newton meter", SIMCONNECT_DATATYPE_FLOAT64, 1.0 },
    { "TURB ENG MAX TORQUE PERCENT:1", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "TURB ENG MAX TORQUE PERCENT:1", "percent", SIMCONNECT_DATATYPE_FLOAT64, 0.05 },
    { "PROP RPM:1", "rpm", SIMCONNECT_DATATYPE_FLOAT64, 1 },
    { "PROP RPM:2", "rpm", SIMCONNECT_DATATYPE_FLOAT64, 1 },
    { "GENERAL ENG EXHAUST GAS TEMPERATURE:1", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.1 },
    { "GENERAL ENG EXHAUST GAS TEMPERATURE:2", "celsius", SIMCONNECT_DATATYPE_FLOAT64, 0.1 }
};

